### ISSUE TITLE
Failed to start. Verify that you have sufficient privliges to start system services.

### ISSUE THREAD

**Issue by Scionist** [camren-m/XboxWheelCompatibility#12] opened 2023-01-15 02:13 UTC
How do i fix this issue?

**Comment by camren-m** [comment] 2023-01-15 03:01
> How do i fix this issue?

When you start the installer, does it prompt you to allow changes to this device or similar?

**Comment by beclugo** [comment] 2023-01-17 03:27
> > How do i fix this issue?
> 
> When you start the installer, does it prompt you to allow changes to this device or similar?

Pop ups the changes on this device but same error.

**Comment by Azeyyy** [comment] 2023-01-18 13:17
Anyone find anything I am going to light myself on fire if I don't figure this out.

**Comment by camren-m** [comment] 2023-01-20 23:04
Duplicate of #7

**Closed as completed by camren-m** 2023-01-20 23:04 UTC
