### ISSUE TITLE
Problem with turning the wheel(left joystick) and left trigger(brake)

### ISSUE THREAD

**Issue by Anderionaw** [camren-m/XboxWheelCompatibility#41] opened 2023-07-03 15:45 UTC
Hi! I've downloaded the program in hope of making my thrustmaster ferrari spyder 456 PC compatible. I've tried it on assetto corsa but the turning of the wheel registers as the left trigger(brake) and the left trigger registers as spinning the wheel. While configuring my controller on steam the wheel registers only in one direction while the left trigger doesn't register at all. I haven't seen anyone encounter this problem. I run windows 11.  Thanks!

**Comment by camren-m** [comment] 2023-07-03 15:47
Please make sure you're using version 1.2.0.

**Comment by Anderionaw** [comment] 2023-07-03 15:53
nevermind it works, i just used content manager.

**Comment by gabrielgameer** [comment] 2023-07-09 01:43
qual gerenciador de conteudo voce usou tem o link?estou com o mesmo problema

**Comment by BomOnTop** [comment] 2023-08-23 07:07
Im having this issue but it remains the same through content manager

**Comment by camren-m** [comment] 2023-08-29 00:28
I believe this is a duplicate of #38.

**Closed as not planned by camren-m** 2023-08-29 00:28 UTC
