### ISSUE TITLE
It says this error, I'm on Windows 10

### ISSUE THREAD

**Issue by 616laj** [camren-m/XboxWheelCompatibility#9] opened 2023-01-03 21:22 UTC
![image png 1ca88df969912900b58b491eaf82f5ec](https://user-images.githubusercontent.com/121903124/210443505-3e32064a-d631-40c3-aa11-f3719dcb43a3.png)

**Comment by camren-m** [comment] 2023-01-04 03:18
Duplicate of #7

**Closed as not planned by camren-m** 2023-01-04 03:19 UTC
