### ISSUE TITLE
Issue with 1.20

### ISSUE THREAD

**Issue by Zalaen** [camren-m/XboxWheelCompatibility#16] opened 2023-01-24 15:17 UTC
I get about 3/4 of the way through the installation, then it stops and tells me it failed to start.
![image](https://user-images.githubusercontent.com/78573070/214332878-d7a50784-7a62-4bce-824d-760c72e909cf.png)
I'm the only one who uses the computer, and I have full admin priveleges.

**Comment by camren-m** [comment] 2023-01-24 15:33
> I get about 3/4 of the way through the installation, then it stops and tells me it failed to start.
> 
> ![image](https://user-images.githubusercontent.com/78573070/214332878-d7a50784-7a62-4bce-824d-760c72e909cf.png)
> 
> I'm the only one who uses the computer, and I have full admin priveleges.

Duplicate of #7. Currently working on a fix.

**Closed as completed** 2023-01-24 15:34 UTC
