### ISSUE TITLE
Build 1.2.0 Issues

### ISSUE THREAD

**Issue by AmericanBranflakes** [camren-m/XboxWheelCompatibility#32] opened 2023-05-02 02:05 UTC
When trying to get the wheel (Thrustmaster Spider 458) working in SCS games, Euro and American Truck Sim, they read wheel inputs as z axis inputs identical to the right pedal. Attempted restart and reinstall before contacting.

**Comment by danielpalfrey** [comment] 2023-05-02 05:14
When mine did this I unplugged the wheel and plugged it back in while the game was running. This did however cause the right click issue I mentioned in my issue request.

**Comment by FutWis** [comment] 2023-07-08 04:36
> 

Did the 1.1 work

**Comment by FutWis** [comment] 2023-07-08 04:36
Because I have the same problem

**Comment by camren-m** [comment] 2023-08-29 00:36
Possible duplicate of #38

**Closed as not planned by camren-m** 2023-08-29 00:36 UTC
