### ISSUE TITLE
problem with lunching

### ISSUE THREAD

**Issue by KarjuPL** [camren-m/XboxWheelCompatibility#6] opened 2022-12-27 10:46 UTC
![Untitled](https://user-images.githubusercontent.com/121490759/209655294-2f387d17-2130-4c67-bf01-19f5c5833fb7.png)

**Comment by camren-m** [comment] 2022-12-27 19:07
Duplicate of #2. Please install the latest version.

**Closed as not planned** 2022-12-27 19:11 UTC
