### ISSUE TITLE
Doesnt work keep getting this

### ISSUE THREAD

**Issue by Truskater1255** [camren-m/XboxWheelCompatibility#11] opened 2023-01-08 06:21 UTC
![image](https://user-images.githubusercontent.com/122196435/211183322-3900292a-f920-40c2-97e7-59643d3f4e6a.png)
![error jpg 58be7f798fd54af2191c607e4dda209e](https://user-images.githubusercontent.com/122196435/211183336-ee1d6a4b-e3a0-482a-aaa5-6feee89be3d8.jpg)
![stuckon jpg 88a142922004764c9a89487102edb9b1](https://user-images.githubusercontent.com/122196435/211183361-1f411cd6-1522-49e7-861b-370bca1fef31.jpg)

KEEP GETTING this on windows 11 please fix it quick if possible want to play games

**Comment by Truskater1255** [comment] 2023-01-08 06:22
I keep getting this on windows 11

**Comment by camren-m** [comment] 2023-01-08 17:43
Duplicate of #7. I'll look into it more when I get home later today.

**Closed as completed by camren-m** 2023-01-08 17:43 UTC

**Comment by Truskater1255** [comment] 2023-01-08 18:51
Okay thank you! please fix it i want to play on my wheel
