### ISSUE TITLE
Wheel not shown in F1-22 and Dirt 2

### ISSUE THREAD

**Issue by realvanion** [camren-m/XboxWheelCompatibility#23] opened 2023-03-17 14:56 UTC
Hey there,

i installed your tool, but my Spider is will not be shown F1-22 or Dirt 2.

Any Idea?

Best reganrds,
Chris

--
Windows 11 Home 22H2
Installation worked
Wheel Comparibility shows "Wheel connected"
Device Management shows "Xbox Gamingdevice"

**Comment by camren-m** [comment] 2023-08-29 00:45
Duplicate of #47.

**Closed as not planned by camren-m** 2023-08-29 00:45 UTC
